### PR TITLE
Added ability to configure namespace

### PR DESCRIPTION
**Pull request by naveed-ahmad**
We were using `App` for something else, so jumped in and added configurable namespace

### CODE REVIEW

**Comment by kpheasey** [comment]
Thanks for updates!  I'll review this over the next few days and let you know.

**Comment by cjjuice** [comment]
:+1:

**Comment by naveed-ahmad** [comment]
@kpheasey what's up with this PR ?

**Comment by kpheasey** [comment]
Sorry, it feel to the side.  I'll review it right now.

**Comment by naveed-ahmad** [comment]
Thanks for quick response :)

**Comment by kpheasey** [comment]
@naveed-ahmad Tested and looking good.

https://github.com/gemgento/rails_script/releases/tag/v0.7.0
https://rubygems.org/gems/rails_script

**Pull request merged**
